#include "woods.inc"
#declare Base_material = material { 
	texture { T_Wood23
	}
}

#include "woods.inc"
#declare Near_Fence_material = material { 
	texture { T_Wood23
	}
}

#include "woods.inc"
#declare Far_Fence_material = material { 
	texture { T_Wood23
	}
}

#include "woods.inc"
#declare Blade_Guard___Left_material = material { 
	texture { T_Wood23
	}
}

#include "woods.inc"
#declare Blade_Guard___Right_material = material { 
	texture { T_Wood23
	}
}

#include "woods.inc"
#declare Blade_Guard___Main_material = material { 
	texture { T_Wood23
	}
}

#include "woods.inc"
#declare Handle_material = material { 
	texture { T_Wood1
	}
}

#include "metals.inc"
#declare Near_Fence_Top_T_Track_material = material { 
	texture { Chrome_Metal
	}
}

#include "metals.inc"
#declare Far_Fence_Top_T_Track_material = material { 
	texture { Chrome_Metal
	}
}

#include "metals.inc"
#declare Base_T_Track___Left_material = material { 
	texture { Chrome_Metal
	}
}

#include "metals.inc"
#declare Base_T_Track___Right_material = material { 
	texture { Chrome_Metal
	}
}

